name: Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-node@v4'
        with:
          node-version-file: 'backend/package.json'

      - run: npm ci
        working-directory: backend

      - run: npm run prettier:lint:check
        working-directory: backend

  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'

      - uses: 'actions/setup-node@v4'
        with:
          node-version-file: 'backend/package.json'

      - run: npm ci
        working-directory: backend

      - run: npm run lint:eslint:check
        working-directory: backend

  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - uses: 'actions/checkout@v4'
        with:
          fetch-depth: 0

      - uses: 'actions/setup-node@v4'
        with:
          node-version-file: 'backend/package.json'

      - run: npm ci

      - run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
        working-directory: backend
