name: Automated Tests
on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version-file: 'backend/package.json'

      - run: npm ci
        working-directory: backend

      - run: npm test
        working-directory: backend
